language: bash

matrix:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64
   - os: linux
     arch: ppc64le
   
script:
  - if [ "$TRAVIS_ARCH" == "ppc64le" ]; then whoami ; fi
  - if [ "$TRAVIS_ARCH" == "ppc64le" ]; then arch; fi
